version: '2'

services:
  node1:
    build:
      context: ./dockerfiles/node
    image: node
    container_name: node1
    expose:
      - 8545
    environment:
      - DOCKER_NAME=node1

  miner1:
    build:
      context: ./dockerfiles/miner
    image: miner
    container_name: miner1
    cpu_quota: 50000
    environment:
      - DOCKER_NAME=miner1

  miner2:
    build:
      context: ./dockerfiles/miner
    image: miner
    container_name: miner2
    cpu_quota: 50000
    environment:
      - DOCKER_NAME=miner2